### PR TITLE
Testing requests

### PR DESCRIPTION
**Pull request by markusressel**
Okay so this is a pretty huge PR with several changes. The main focus is obiously on tests but I had to change some other things to be able to write useful tests. Don't feel overwhelmed by the amount of "code" in this PR. Most of it are just the json files containing demo http request responses that are used inside the tests.

To run all tests you can simply execute `nosetests` from the root directory of this repo. It should output something like this:

```
(venv) [markus@Silver python-n26]$ nosetests
...............................
----------------------------------------------------------------------
Ran 31 tests in 0.725s

OK
```

This improves #3 by a lot, but still doesn't cover all the things.

## Tests
* Added `json` files for many of the supported API methods (not all are integrated yet, but all that are accessible from the cli + a couple more)
* Added decorator `mock_requests` to easily mock http request responses
* Added possibility to test cli commands in a better way
* Complete rewrite of all testing code using `unittest.TestCase`
  * API
    * Auth token tests
    * Config tests
  * Account
    * `get_account_info`
    * `get_account_statuses`
    * `get_account_limits`
    * `get_addresses`
    * `get_contacts`
    * `get_statements`
    * `get_account_info`
    * `get_account_info`
  * Balance (`get_balance`)
  * Cards
    * `get_cards`
    * `card_block`
    * `card_unblock`
  * Spaces (`get_spaces`)
  * Statistics (`get_statistics`)
  * Transactions (`get_transactions`)
## Config
* extracted constants to global vars (for testing purposes)
## Api
* refactored code to create request url with parameters to a separate function `_create_request_url` (again to be able to test it)
* added many missing type information
* added parameters to `transactions` cli command
  * `--categories`
  * `--pending`
  * `--from`
  * `--to`
  * `--text-filter`
* improved `transactions` cli output

If you have any question you know how to contact me :nerd_face:

### CODE REVIEW

**Comment by sublinus** [comment]
What is the motivation in switching from pytest to unittest?
The test target in the Makefile, setup.py and Pipfile should be updated to not break because of the change in the testing system.

**Comment by markusressel** [comment]
pytest can also run unittest Tests. I just gave nosetests as an example command because I used it in other projects. I Used unittest testcase classes because it allows inheritance.

**Comment by markusressel** [comment]
pytest works just fine:

```
> pytest                                                                   0 < 11:55:21
================================= test session starts =================================
platform linux -- Python 3.6.8, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/markus/programming/PycharmProjects/python-n26
collected 31 items                                                                    

tests/test_account.py ..........                                                [ 32%]
tests/test_api.py .....                                                         [ 48%]
tests/test_balance.py ..                                                        [ 54%]
tests/test_cards.py .....                                                       [ 70%]
tests/test_config.py ...                                                        [ 80%]
tests/test_spaces.py ..                                                         [ 87%]
tests/test_statistics.py ..                                                     [ 93%]
tests/test_transactions.py ..                                                   [100%]

============================== 31 passed in 1.21 seconds ==============================
```

**Comment by markusressel** [comment]
I just realized that the tests only work if a config file is present in the `.config` folder.
I need to change this before merging.

**Comment by markusressel** [comment]
> I just realized that the tests only work if a config file is present in the `.config` folder.
> I need to change this before merging.

It's fixed now. 
By default the `test_creds.yml` file will now be used for config.
If config code should be skipped completely there is the `mock_config` decorator to set custom config values per test.

**Comment by markusressel** [comment]
@femueller any thoughts on how to progress with this? I'm very much willing to invest more time into this but won't take any action without your permission :nerd_face:

**Comment by femueller** [comment]
As discussed in private I guess we can go ahead with these tests 👍.

**Pull request merged**
